export const users = [
  {
    id: 1,
    avatar: `https://randomuser.me/api/portraits/women/10.jpg`,
    name: 'Ana Carolina Silva',
    email: 'anacarolina-silva@email.com',
    role: 'customer',
    status: 'active',
    created_at: 'November 07, 2022',
  },
  {
    id: 2,
    avatar: `https://randomuser.me/api/portraits/women/8.jpg`,
    name: 'Maria Eduarda Oliveira',
    email: 'maoliveira@email.com',
    role: 'customer',
    status: 'inactive',
    created_at: 'November 02, 2020',
  },
  {
    id: 3,
    avatar: `https://randomuser.me/api/portraits/men/22.jpg`,
    name: 'João Gabriel Santos',
    email: 'ggsantos@email.com',
    role: 'customer',
    status: 'active',
    created_at: 'August 21, 2020',
  },
  {
    id: 4,
    avatar: `https://randomuser.me/api/portraits/women/18.jpg`,
    name: 'Dede Iowarch',
    email: 'dede-iowarch@email.com',
    role: 'customer',
    status: 'active',
    created_at: 'January 31, 2021',
  },
  {
    id: 5,
    avatar: `https://randomuser.me/api/portraits/women/4.jpg`,
    name: 'Camilla Oliveira Souza',
    email: 'camillasouza98@email.com',
    role: 'customer',
    status: 'inactive',
    created_at: 'October 24, 2023',
  },
  {
    id: 6,
    avatar: `https://randomuser.me/api/portraits/men/24.jpg`,
    name: 'Thiago Almeida Pereira',
    email: 'thiagoapereira@email.com',
    role: 'admin',
    status: 'active',
    created_at: 'March 16, 2021',
  },
  {
    id: 7,
    avatar: `https://randomuser.me/api/portraits/women/28.jpg`,
    name: 'Isabela Cristina Lima',
    email: 'limaisabela@email.com',
    role: 'customer',
    status: 'active',
    created_at: 'September 29, 2021',
  },
  {
    id: 8,
    avatar: `https://randomuser.me/api/portraits/women/32.jpg`,
    name: 'Gabriel Oliveira',
    email: 'oliveirago@email.com',
    role: 'admin',
    status: 'active',
    created_at: 'September 29, 2020',
  },
  {
    id: 9,
    avatar: `https://randomuser.me/api/portraits/men/36.jpg`,
    name: 'Nicolas Henrique Couto',
    email: 'nicolascouto@email.com',
    role: 'customer',
    status: 'active',
    created_at: 'September 15, 2022',
  },
  {
    id: 10,
    avatar: `https://randomuser.me/api/portraits/men/40.jpg`,
    name: 'Pedro Henrique Costa',
    email: 'pedrohcosta@email.com',
    role: 'customer',
    status: 'inactive',
    created_at: 'August 21, 2022',
  },
];

export const statuses = {
  active: 'green',
  inactive: 'red',
};
